linux checks, etc...

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -39,7 +39,17 @@ jobs:
             - name: install system dependencies
               run: |
                   sudo apt-get update
-                  sudo apt-get install -y dpkg-dev build-essential libxi-dev libx11-dev libxext-dev
+                  sudo apt-get install -y
+                      dpkg-dev \
+                      build-essential \
+                      libxi-dev \
+                      libx11-dev \
+                      libxext-dev \
+                      libgl1-mesa-dev \
+                      libglu1-mesa-dev \
+                      libglfw3-dev \
+                      libglew-dev \
+                      xorg-dev
 
             - name: ensure build script perms
               run: chmod +x ./elter.sh
@@ -49,6 +59,13 @@ jobs:
 
             - name: build linux binary
               run: ./elter.sh --build
+
+            - name: check if binary exists
+              run: |
+                  if [ ! -f "build/elterclick" ]; then
+                      echo "binary not found!"
+                      exit 1
+                  fi
 
             - name: upload linux artifacts
               uses: actions/upload-artifact@v4
@@ -81,6 +98,13 @@ jobs:
 
             - name: build windows binary
               run: powershell ./elter.ps1 --build
+
+            - name: check if binary exists
+              run: |
+                  if (!(Test-Path "build/elterclick.exe")) {
+                      Write-Error "Error: Binary not found!"
+                      exit 1
+                  }
 
             - name: upload linux artifacts
               uses: actions/upload-artifact@v4
